language: node_js

node_js:
  - "5"
  - "stable"

install:
  - npm install -g gulp@3.9.0 --save-dev
  - npm install --global yo gulp-cli bower
  - npm install --save-dev babel-register
  - npm install
  - bower install
  - npm link gulp
 
script:
  - gulp build

after_success:
  - gulp package

notifications:
  email: 4296411@qq.com
