language: node_js

node_js:
  - "5"
  - "stable"

install:
  - npm install -g gulp@3.9.0
  - npm install --global gulp@3.9.0 yo gulp-cli bower
  - npm install --save-dev gulp babel-register
  - bower install
  - npm install
 
script:
  - gulp babel
  - gulp build

after_success:
  - gulp package

notifications:
  email: 4296411@qq.com
