language: node_js

node_js:
  - "5"
  - "stable"

install:
  - npm install -g gulp
  - npm install --save-dev gulp
  - npm install --global yo gulp-cli bower
  - npm install --save-dev babel-register
  - npm install
  - bower install
 
script:
  - gulp build

after_success:
  - gulp package

notifications:
  email: 4296411@qq.com
